services:
  fastapi:
    build:
      context: .
      dockerfile: compose/Dockerfile
    image: book_recommendation_system
    container_name: book_recommendation_api
    ports:
      - "8000:8000"
    volumes:
      - .:/app
